### PR TITLE
Improving README file - Windows & DB setup

### PR DESCRIPTION
**Pull request by nsunami**
Hi! I was able to run the app on Windows as well, and I thought it may be helpful to update the README file with the info that I learned so far.

Hope this helps 🤞

### CODE REVIEW

**Comment by roelj** [comment]
Hi @nsunami. Thank you for taking the time to revise the README. It's much appreciated.

There are a few unneccessary changes (like the formatting of the title, the removal of double spaces after a dot).

And there are a few things we need to revise before accepting the pull request:
- When referring to "Linux", we prefer "GNU/Linux"; Most of the tools we actually interact with are part of GNU. :-)
- We don't recommend using Docker containers, so instead, could we just point to the installation instructions or READMEs of the SPARQL 1.1 implementations?
- I think this instruction is only for Fuseki:
```
Login to the database Admin panel to create a dataset for djehuty named `sparql`. (new dataset -> create dataset named `sparql`)
```
Is there are way to mark it as such? :-)

Thank you again for your time and efforts!

**Comment by roelj** [comment]
Hi @nsunami! Would it be okay with you if I propose a revised patch and then accept the pull request after you've reviewed it? :-)

Thank you.

**Comment by nsunami** [comment]
> Hi @nsunami! Would it be okay with you if I propose a revised patch and then accept the pull request after you've reviewed it? :-)
> 
> 
> 
> Thank you.

That's ok by me!

**Comment by roelj** [comment]
Hi @nsunami . I've prepared a revision at [pr-update-readme](https://github.com/4TUResearchData/djehuty/compare/main...pr-update-readme).

Would this work for you? Thank you again for your time.

**Comment by nsunami** [comment]
I commented on your [commit](https://github.com/4TUResearchData/djehuty/commit/a1db8b3334e92f8d4d7b02d6207be4e66c35bf4a)--looks good to me!

**Comment by roelj** [comment]
Thank you again for your efforts in proposing and reviewing the updates to the README. :-) I pushed the change in [f3dbca17](https://github.com/4TUResearchData/djehuty/commit/f3dbca17d08cadd73f4481a3da4c690ad4046e83)

**Pull request closed without merging**
